package com.campsuvival.campsuvivalmod;

import net.minecraft.block.Block;
import net.minecraft.client.renderer.block.model.ModelResourceLocation;
import net.minecraft.item.ItemBlock;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.client.model.ModelLoader;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.registry.GameRegistry;

@Mod(modid = CampSurvivalMod.MODID, version = CampSurvivalMod.VERSION)
public class CampSurvivalMod
{
    public static final String MODID = "campsurvivalmod";
    public static final String VERSION = "0.1";
    public static final String MOD_VERSION = "0.0.1";
    public static final String MOD_DEPENDENCIES = "required-after:Forge@[1.10.2-12.18.3.2254,)";
    public static final String MOD_ACCEPTED_MC_VERSIONS = "[1.10.2]";
    //Modの情報を格納する。 mcmod.infoの上位互換
    @Mod.Metadata
    public static ModMetadata metadata;
    /** Woodenframeのブロックのインスタンスを格納する */
    public static Block woodenframeblock;
    @EventHandler
    public void preInit(FMLPreInitializationEvent event){
        loadMeta();
        woodenframeblock = new WoodenFrameBlock();
        //ブロックの登録。登録文字列はMOD内で被らなければ何でも良い。
        ResourceLocation registryName = new ResourceLocation(MODID, "woodenframeblock");
        ItemBlock woodenframeitemblock = new ItemBlock(woodenframeblock);
        GameRegistry.register(woodenframeblock, registryName);
        GameRegistry.register(woodenframeitemblock, registryName);


        //テクスチャ・モデル指定JSONファイル名の登録
        if(event.getSide().isClient()) {
            ModelLoader.setCustomModelResourceLocation(woodenframeitemblock, 0, new ModelResourceLocation(new ResourceLocation(MODID, "woodenframeblock"), "inventory"));
        }


    }
    private void loadMeta() {
        metadata.authorList.add("bagu_chan");
        metadata.modId = MODID;
        metadata.name = MODID;
        metadata.version = VERSION;
        // Modのアップデートをチェックする為のJson 詳細は、 https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/ 参照
        // metadata.updateJSON
        //これをfalseにしておかないと、ModMetadataが読み込まれない
        metadata.autogenerated = false;
    }
}